GET  http://localhost:5000/clients

###
GET  http://localhost:5000/users/1





###
POST http://localhost:5000/clients
Content-Type: application/json

{
  "nama": "Bayu",
  "alamat": "Indonesia",
  "Contact": "1234567890",
  "Layanan": "Legal Consultation",
  "Kategori": "Corporate Law",
  "Status": "Ongoing",
  "tglMasuk": "2024-08-28",
  "tglSelesai": "2024-09-05",
  "deskripsi": "ho ho hi hie"
}


###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "jarot",
    "email": "jarot@gmail.com",
    "gender": "Male"
}

###
DELETE  http://localhost:5000/users/2
